name: env_sis421
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - librosa
  - matplotlib
  - numpy
  - opencv
  - pip
  - pip:
    - ai-edge-torch
    - mediapipe
    - grad-cam
    - tqdm
